# Generated by Django 4.0.4 on 2022-05-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPoints',
            new_name='UserPoint',
        ),
    ]
